#Requires -Version 7.0
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string] $RepositoryRoot,
    [Parameter(Mandatory)][string] $OutputPath,
    [switch] $RequireGit
)

$ErrorActionPreference = 'Stop'
$identity = & (Join-Path $RepositoryRoot 'scripts/version.ps1') show -RepositoryRoot $RepositoryRoot -Json -RequireGit:$RequireGit | ConvertFrom-Json
$parts = @([string]$identity.numericVersion -split '\.')
$assemblyVersion = "$($parts[0]).$($parts[1]).0.0"
$fileVersion = [string]$identity.numericVersion

function Escape-CSharp([string] $Value) { $Value.Replace('\', '\\').Replace('"', '\"') }

$content = @"
// <auto-generated />
using System.Reflection;

[assembly: AssemblyVersion("$(Escape-CSharp $assemblyVersion)")]
[assembly: AssemblyFileVersion("$(Escape-CSharp $fileVersion)")]
[assembly: AssemblyInformationalVersion("$(Escape-CSharp ([string]$identity.informationalVersion))")]
[assembly: AssemblyMetadata("MoDiBuild", "$(Escape-CSharp ([string]$identity.build))")]
[assembly: AssemblyMetadata("MoDiVersionCode", "$(Escape-CSharp ([string]$identity.build))")]
[assembly: AssemblyMetadata("MoDiCommit", "$(Escape-CSharp ([string]$identity.commit))")]
[assembly: AssemblyMetadata("MoDiChannel", "$(Escape-CSharp ([string]$identity.channel))")]
[assembly: AssemblyMetadata("MoDiReleaseIdentity", "$(Escape-CSharp ([string]$identity.releaseIdentity))")]
"@

$parent = Split-Path -Parent ([IO.Path]::GetFullPath($OutputPath))
[IO.Directory]::CreateDirectory($parent) | Out-Null
[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputPath), $content, [Text.UTF8Encoding]::new($false))
